# -*- coding: utf-8 -*-
"""NSigmaChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcrMTnmuZWdNIWF8zYrH0fbEe2R7tgn0
"""

!pip install -U google-generativeai

import google.generativeai as genai

genai.configure(api_key='AIzaSyAekADtT70nHvL-_I058I_1PICLjtkilEM')

import json

# Load the data from JSON files
with open('/content/biographical_info.json', 'r') as bio_file:
    bio_data = json.load(bio_file)

with open('/content/songs_data.json', 'r') as song_file:
    songs_data = json.load(song_file)

def chat_with_nsigma():
    nsigma_context = "NSigma is an American hip-hop artist known for his music with deep messages. He combines rapid-fire rap flows with autotune-infused melodies."

    # Initial chat conversation setup with NSigma context
    response = genai.chat(messages=[{"author": "system", "content": nsigma_context}, {"author": "user", "content": "Hello"}])
    print("Chatbot:", response.last)  # Print the initial response from the chatbot

    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("Chatbot: Goodbye!")
            break

        user_input_lower = user_input.lower()
        if "who is nsigma" in user_input_lower or "tell me about nsigma" in user_input_lower:
            print("Chatbot:", bio_data['biography'])

        elif "lyrics" in user_input_lower or "annotations" in user_input_lower:
            song_name = user_input.replace('lyrics', '').replace('annotations', '').strip()
            for song in songs_data:
                if song['title'].lower() in song_name.lower():
                    if 'lyrics' in user_input_lower:
                        lyrics_info = '\n'.join(f"{line['section']}: {line['text']}" for line in song['lyrics'])
                        print("Chatbot - Lyrics:", lyrics_info)
                    if 'annotations' in user_input_lower:
                        annotations_info = '\n'.join(f"Annotation: {note['text']} - {note['annotation']}" for note in song['annotations'])
                        print("Chatbot - Annotations:", annotations_info)
                    break
            else:
                # If no specific lyrics or annotations found, continue with general conversation
                response = genai.chat(messages=[{"author": "system", "content": nsigma_context}, {"author": "user", "content": user_input}])
                print("Chatbot:", response.last)

        else:
            found_song = False
            for song in songs_data:
                if song['title'].lower() in user_input_lower:
                    song_info = f"{song['title']} from the album {song['album']['name']} released on {song['album']['release_date']}. Description: {song['description']}"
                    print("Chatbot:", song_info)
                    found_song = True
                    break
            if not found_song:
                # Continue the conversation with the model if no song match is found
                response = genai.chat(messages=[{"author": "system", "content": nsigma_context}, {"author": "user", "content": user_input}])
                print("Chatbot:", response.last)

# Run the chat function
chat_with_nsigma()